site_name: Conk
nav:
  - Home: index.md
  - About: about.md
  - Zonk:
    - Introduction: usermanual/zonk/introduction.md
    - Game: usermanual/zonk/game.md
    - Display: usermanual/zonk/display.md
    - ActionLists: usermanual/zonk/actionlists.md
    - Actions: usermanual/zonk/actions.md
    - Weapons: usermanual/zonk/weapons.md
    - Paths: usermanual/zonk/paths.md
    - ScrollWaves: usermanual/zonk/scrollwaves.md
    - Formation: usermanual/zonk/formation.md
    - Timed Attackwaves: usermanual/zonk/timedattackwaves.md
    - Sound Effects: usermanual/zonk/soundfx.md
    - Edge Of the Road: usermanual/zonk/eotr.md
  - Gonk:
    - Introduction: usermanual/gonk/introduction.md
    - Tools: usermanual/gonk/tools.md
    - Menu: usermanual/gonk/menus.md
    - Keyboard Shortcuts: usermanual/gonk/shortcuts.md
    - Windows: usermanual/gonk/windows.md
  - Bonk:
    - Introduction: usermanual/bonk/introduction.md
    - Menus: usermanual/bonk/menus.md

theme: readthedocs
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list