site_name: Conk
nav:
  - Home: index.md
  - About: about.md
  - Gonk:
    - Index: usermanual/gonk/index.md
    - Menu: usermanual/gonk/menu.md
    - Windows: usermanual/gonk/windows.md
theme: readthedocs